name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install make
      run: sudo apt install -y make

    - name: Install dependencies (build)
      run: make

    - name: Install to local directory
      run: |
        # Run 'make install' with a custom DESTDIR to install to a local directory
        make DESTDIR=$(pwd)/install install

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./install/bin

