name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install make
      run: sudo apt install make
      
    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Upload build artifacts
      if: success()  # Only upload if the job is successful
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts  # Name of the artifact
        path: ./linux-x86-generic-build-build-against-libc6-old  # Path to the files or directories you want to upload

